### ISSUE TITLE
プラグインの紹介ページにREADMEを掲載

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#109]
## 問題意識

プラグインの説明が不足している。

## 解決方法

READMEをDetailタグで掲載する。`web`でMarkdownファイルを指定している場合に限る。

**Comment by JG1VPP** [comment]
## 実装

`zbuild market`の実行中に、あるプラグインの`web`の拡張子が`.md`ならダウンロードし、その内容をJSONに格納する。サイト構築時に、その内容を展開する。

**Comment by JG1VPP** [comment]
そもそも、プラグインの説明をマニュアルに掲載しているのは本末転倒なので、最低限のドキュメントを残して、プラグインの一覧ページに説明を移動する。

**Comment by JG1VPP** [comment]
既に https://use.zlog.org/plugins に投入済み。プラグイン側では順次Markdownを配置予定。

## 実装

`market.toml`で`web`が設定されている場合、その内容が`market.json`の`doc`要素に格納される。

### .mdファイルの場合

Markdownとして処理され、プラグインの紹介に表示される。

### それ以外の場合

単にHTMLとして処理され、タグを外した状態で表示される。代替表示なので、マーケット管理人は速やかにMarkdownに差し替えること。

**Comment by JG1VPP** [comment]
@jucky154 対応お願いします。README.mdとは別に、usage.mdなどをレポジトリに置き、そのファイルを参照するように`doc`を設定してください。

```toml
[pkg.aktest]
tag = "旭川コンテスト"
msg = "旭川コンテストのCFGファイルと, 正確な得点計算を行うプラグインです."
web = "https://github.com/nextzlog/zylo"
doc = "https://raw.githubusercontent.com/nextzlog/zylo/master/plugins/rules/aktest/README.md"
use = ["dll.aktest", "cfg.aktest"]
exp = "stable"
```
