### ISSUE TITLE
docker-composeでnginxも同時に起動する

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#137]
## 問題意識

https://github.com/nextzlog/todo/issues/135 でフロントエンドサーバにより`/admin`以下を秘匿する旨を案内しているが、どうせならdocker-composeでnginxも起動してしまい、そこで設定を同時に済ませてしまう方が、導入の障壁を下げるだろう。

## 解決方法

`docker-compose.yaml`にnginxの起動設定を追加する。

**Comment by JG1VPP** [comment]
## 起動手順

```sh
$ docker-compose up -d
```

## 必要なファイル

#### `docker-compose.yaml`

```yaml
version: '3'
services:
  ATS4:
    image: ghcr.io/nextzlog/ats4:master
    ports:
    - 9000:9000
    volumes:
    - ./ats/data:/ats/data
    - ./ats/logs:/ats/logs
    - ./application.conf:/ats/conf/application.conf
    command: /ats/bin/ats4
  www:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
```

#### `application.conf`

```ini
# Application secret
play.http.secret.key = "SxhjJYZkuA>tf9kkSR97z1LBJ`_5SpSXz4 = 1v5Rqm_JxNR^^cDODT8d1H^cPW@y:"

# Hostname
play.filters.hosts.allowed = ["localhost", "ats4"]

# Error Handler
play.http.errorHandler = "controllers.Error"

# Cache-Control
play.filters.enabled += "controllers.Cache"
cache.control = "no-cache, no-store, must-revalidate"

# Modules
play.modules.enabled += "injects.Ats4Module"

# Contest
ats4.rules = "/rules/JH8LEF/1am.rb"

# Database
db.default.driver = org.h2.Driver
db.default.url = "jdbc:h2:file:./data/ats4"
db.default.username = sa
db.default.password = ""

# Typesafe mailer plugin
play.mailer.host = example.com
play.mailer.port = 465
play.mailer.ssl = true
play.mailer.user = mail
play.mailer.password = password
play.mailer.mock = true

# Real-Time contest settings
rtc.delay = 5

# QSO input
ats4.bands = [
	"1.9MHz",
	"3.5MHz",
	"7MHz",
	"14MHz",
	"21MHz",
	"28MHz",
	"50MHz",
	"144MHz",
	"430MHz",
	"1.2GHz",
	"2.4GHz",
	"5.6GHz"
]

ats4.modes = [
	"CW",
	"SSB",
	"FM",
	"AM",
	"RTTY"
]
```

#### `default.conf`

```conf
server {
  server_name localhost;
  location / {
    proxy_pass http://ATS4:9000;
    location /admin/ {
      allow 127.0.0.1;
      deny all;
    }
    location ~ /admin {
      allow 127.0.0.1;
      deny all;
    }
  }
}
```
