### ISSUE TITLE
GitHub Actionsの定期実行は60日で停止する

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#171]
## 概要

GitHub Actionsではコミットがない状態で60日放置すると、cron実行が停止される。

### 対象

以下が影響を受ける。特にマーケットプレイスが勝手に更新停止される可能性がある。

- autodyne/nextzlog.dev
- nextzlog/use.zlog.org
- nextzlog/dev.zlog.org
- nextzlog/pkg.zlog.org

### 対策

検討中。コミットがあれば停止しないが、安易な解決策に頼るのは...

**Comment by JG1VPP** [comment]
nextzlog/todo のIssuesを拾っている autodyne/nextzlog.dev や nextzlog/dev.zlog.org は、Issueをトリガーにすればcronの影響を受けない。

**Comment by JG1VPP** [comment]
nextzlog/pkg.zlog.org については、[手動でWorkflowを再起動](https://github.com/nextzlog/pkg.zlog.org/actions/workflows/build.yaml)できる。

**Comment by JG1VPP** [comment]
## 対策

cronによる定期実行の際にワークフローを有効化し続ける:

```yaml
on:
  push:
    branches:
    - 'master'
  schedule:
  - cron: '5 0 * * *'
  workflow_dispatch:
permissions:
  actions: write
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  Sustain:
    runs-on: ubuntu-latest
    steps:
    - run: gh workflow enable build.yaml
      env:
        GH_REPO: ${{github.repository}}
```
