### ISSUE TITLE
1エリアAMコンテストの起動用バイナリ

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#196]
## 問題意識

1エリアAMコンテストのメール受付による半自動集計のため、Windowsで動作する実行可能ファイルを準備する。

## 解決方法

Docker composeを実行する実行可能ファイルを実装する。

**Comment by JG1VPP** [comment]
## 実装

### go

```go
package main

import (
	_ "embed"
	"os"
	"os/exec"
)

//go:embed docker-compose.yaml
var compose []byte

func main() {
	os.WriteFile("docker-compose.yaml", compose, 0666)
	cmd := exec.Command("docker", "compose", "up")
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Run()
}
```

### docker compose

```yaml
version: '3'
services:
  ATS4:
    image: ghcr.io/nextzlog/ats4:master
    ports:
    - 80:9000
    volumes:
    - ./ats/data:/ats/data
    - ./ats/logs:/ats/logs
    command: /ats/bin/ats4
    environment:
      TZ: Asia/Tokyo
      ATS4_MAIL_MOCK: true
      ATS4_RULE_FILE: /rules/1am.rb
```

**Comment by JG1VPP** [comment]
## 実行方法

1. Docker Desktopをインストールする
2. `ats4-1am.exe`をダブルクリックで実行する
3. ブラウザが自動的に開く
4. しばらく待ってからブラウザを更新する

**Comment by JG1VPP** [comment]
## 実行可能ファイル

[ats4-1am.zip](https://github.com/nextzlog/todo/files/12841529/ats4-1am.zip)

**Comment by JG1VPP** [comment]
## 実装

### go

```go
package main

import (
	"bufio"
	_ "embed"
	"github.com/pkg/browser"
	"os"
	"os/exec"
	"strings"
)

//go:embed docker-compose.yaml
var compose []byte

func main() {
	writer := bufio.NewWriter(os.Stdout)
	defer exec.Command("docker", "compose", "down").Run()
	os.WriteFile("docker-compose.yaml", compose, 0666)
	cmd := exec.Command("docker", "compose", "up")
	out, _ := cmd.StdoutPipe()
	buff := make([]byte, 1024)
	cmd.Start()
	text := ""
	for true {
		if n, _ := out.Read(buff); n > 0 {
			writer.Write(buff[:n])
			writer.Flush()
			text += string(buff[:n])
			if strings.Contains(text, "Listening for HTTP") {
				browser.OpenURL("http://localhost")
			}
		} else {
			break
		}
	}
}
```

### docker compose

```yaml
version: '3'
services:
  ATS4:
    image: ghcr.io/nextzlog/ats4:master
    ports:
    - 80:9000
    volumes:
    - ./ats/data:/ats/data
    - ./ats/logs:/ats/logs
    command: /ats/bin/ats4
    environment:
      TZ: Asia/Tokyo
      ATS4_MAIL_MOCK: true
      ATS4_RULE_FILE: /rules/1am.rb
```

## ダウンロード

[ats4-1am.zip](https://github.com/nextzlog/todo/files/12841529/ats4-1am.zip)

## 実行方法

1. Docker Desktopをインストールする
2. `ats4-1am.exe`をダブルクリックで実行する
3. ブラウザが自動的に開く
