### ISSUE TITLE
総務省APIプラグイン等の更新

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#42]
**問題意識**

対応しているzLog APIが古く、使用できない。

**解決方法**

ビルドし直す。というか、cronによる自動ビルドを組めば、常に最新のzLog APIに更新される。

**Comment by JG1VPP** [comment]
## 例

以下のように設定すれば、毎日0時(UTC)にビルドされる。
cronの日時指定は[このページ](https://www.yoheim.net/blog.php?q=20190902)が参考になります。

```yaml
name: 'build'
on:
  push:
    branches:
    - 'main'
  schedule:
  - cron: '0 0 * * *'
  BuildDLL:
    runs-on: ubuntu-latest
    steps:
    - uses: nextzlog/zylo@master
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        directory: /path/to/golang/files
```

**Comment by jucky154** [comment]
https://github.com/jucky154/soumuAPI/blob/main/.github/workflows/main.yml
こういう感じでしょうか？

**Comment by JG1VPP** [comment]
上の`/path/to/golang/files`をレポジトリ内でgoファイルのあるディレクトリに変更するだけです。15行目以降は不要です。

**Comment by jucky154** [comment]
https://github.com/jucky154/soumuAPI/blob/main/.github/workflows/main.yml
にしたもののactionを見るとダメぽいですね…（なんかvalid nameが何らかのエラーを入っているぽい…）

**Comment by JG1VPP** [comment]
jobsが抜けてました（修正した）

**Comment by JG1VPP** [comment]
上のサンプルコードにjobsが抜けてました（ので修正した）

**Comment by jucky154** [comment]
https://github.com/jucky154/soumuAPI/blob/main/.github/workflows/main.yml
だと
No files matching the glob pattern found
というエラーですね

**Comment by JG1VPP** [comment]
[directory](https://github.com/nextzlog/zylo/blob/3605e3fb4acef419917a6c9efe050ef600bb6d28/action.yaml#L19-L22)を正しいパスに設定する必要があります。goファイルはレポジトリ直下にあるので、

```yaml
directory: .
```

となります。省略すると、デフォルトでこれと同じ設定になります。

**Comment by jucky154** [comment]
cwtrainerおよび総務APIの方、対応しておきました

**Comment by JG1VPP** [comment]
安定版(stable plugin)に設定しますか？[marketplace](https://zylo.pafelog.net/market)

**Comment by jucky154** [comment]
cwtrainerはstableでいいと思います（いろいろ追加したいのですがその場合正直、抜本的にやり直すべきなので…）
APIの方はメニューを作ってからかなと思っています

**Comment by JG1VPP** [comment]
[rules.toml](https://github.com/nextzlog/zylo/blob/master/markets/rules.toml#L6)に倣って、[market.toml](https://github.com/jucky154/manage_zylo/blob/main/market.toml)で以下のように`exp`を設定することで、stableになります。

```toml
[pkg.lipsum]
tag = "lipsum.DLL"
msg = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
web = "https://etaoinshrdlu.jp"
use = ["dll.lipsum", "cfg.lipsum"]
exp = "stable"
```
