### ISSUE TITLE
market.tomlの修正

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#48]
**概要**

[jucky154/manage_zylo](https://github.com/jucky154/manage_zylo/blob/main/market.toml)に構文エラーがあり、マーケットプレイスの更新が停止している。

**修正**

[`["dll.infoEs"]`](https://github.com/jucky154/manage_zylo/blob/9f04ca17d1191b7e2db571af56870c3182847ff1/market.toml#L37)は、`dll.infoEs`という名前のテーブルを作成しているが、正しくは、`dll`テーブルの中に`infoEs`テーブルを作成する必要がある。なので、引用符を外す必要がある。

**Comment by JG1VPP** [comment]
`yj`コマンドでYAMLに変換するとわかりやすいですね:

```yaml
dll:
  soumu:
    url: https://github.com/jucky154/soumuAPI/releases/download/nightly/soumuAPI.dll
  cwtrain:
    url: https://github.com/jucky154/cwtrainer/releases/download/nightly/cwtrainer.dll
cfg:
  cwtrain:
    url: https://raw.githubusercontent.com/jucky154/cwtrainer/main/cwtrainer.cfg
dat:
  cwtrain:
    url: https://raw.githubusercontent.com/jucky154/cwtrainer/main/cwtrainer.dat
txt:
  cwtrain:
    url: https://raw.githubusercontent.com/jucky154/cwtrainer/main/callsigns.txt
dll.infoEs:
  url: https://github.com/jucky154/infoEs/releases/download/nightly/infoEs.dll
```
