### ISSUE TITLE
チェックサムの必須化

### ISSUE THREAD

**Issue by JG1VPP** [nextzlog/todo#89]
## 問題意識

#83 の対応のため、チェックサムの設定をマーケット管理人の責任とする。

## 解決方法

`market.toml`に、`url`に加え`sum`の指定を必須とした。

```toml
[cfg.hstest]
url = "https://raw.githubusercontent.com/nextzlog/zylo/master/plugins/rules/hstest/hstest.cfg"
sum = "https://raw.githubusercontent.com/nextzlog/zylo/master/plugins/rules/hstest/hstest.cfg.md5"
```

`sum`はチェックサムでも良いし、チェックサムを記したmd5ファイルのURLでも良い。基本的には、URLとした方が良い。

**Comment by JG1VPP** [comment]
## 移行措置

`sum`が未指定の場合は`url`の末尾に`.md5`を加えた値がチェックサムのURLとなる。

**Comment by JG1VPP** [comment]
@jucky154 DLLについて、以下のように`market.toml`に`sum`を設定していただけますか？DLL以外には設定しないでください。

```toml
[dll.FOOBAR]
url = "FOOBAR.dll"
sum = "FOOBAR.dll.md5"
```
